server:
  port: 8081

#MongoDb Config
spring:
  application:
    name: product-service
  zipkin:
    base-url: http://localhost:9411/
sleuth:
  sampler:
    probability: 1

  data:
    mongodb:
      host: localhost
      port: 27017
      database: test
logging.logstash:
  enabled: true
  logheaders: true
  url: http://localhost:5000
logging:
  file:
    path: /home/sam/Documents/SA/Final\ Project/webstore/logs
    name: app_log.log